### PR TITLE
Improve GitHub integration

### PR DESCRIPTION
**Pull request by stweil**
* Use the full license text (generated using GitHub). Now GitHub can automatically detect and show the license in the information bar of the repository.

* Enhance and format the README, so it is more informative in GitHub.

### CODE REVIEW

**Comment by stweil** [comment]
See https://github.com/stweil/tessdata_fast for the new look with this PR applied.

If this PR is accepted, I'd add the same changes to the other tessdata* repositories.
In addition, I suggest adding GitHub tags (`tesseract`, `tesseract-ocr`) to all repositories.
For https://github.com/tesseract-ocr/tessdata, a short description in GitHub would be useful.

**Comment by Shreeshrii** [comment]
>This repository contains language data for the Tesseract Open Source OCR Engine.

I always found this line confusing, since we have `langdata` repo also.

I would suggest using the description used in repo heading - something on the lines of ...

This repository contains Fast integer versions of trained LSTM models  for the Tesseract Open Source OCR Engine.

**Comment by stweil** [comment]
@Shreeshrii, like [this one](https://github.com/stweil/tessdata_best)? I found it confusing, too.

**Comment by Shreeshrii** [comment]
Yes, that's good. Thanks!

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Pull request merged**
