### PR TITLE
Add tessconfigs submodule and links for required tessdata files

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Request for comments. This is a possible solution how a local clone of `tessdata_fast` (and similar the other tessdata* repositories) can be used with Tesseract. It adds the necessary directories `configs` and  `tessconfigs` and the file `pdf.ttf` as symbolic links into the submodule.

**Comment by Shreeshrii** [comment]
Thanks! This will be useful.

Does this add the whole tesseract repo as a submodule or only the required subfolders?

**Comment by Shreeshrii** [comment]
In case it pulls in the whole repo, how about pulling out the directories `configs` and `tessconfigs` and the file `pdf.ttf` into a new `tessdata_configs` repo and then including that as a submodule into tesseract as well as tessdata, tessdata_fast and tessdata_best.

**Comment by stweil** [comment]
It is the whole repository.

The [alternative way](http://blog.davidecoppola.com/2015/02/how-to-create-git-submodule-from-repository-subdirectory/) is to create a new repository (I'd name it just `tesseract-ocr/configs` or `tesseract-ocr/tessconfigs`, not `tesseract-ocr/tessdata_configs`), fill it with the data from [tesseract/tessdata](https://github.com/tesseract-ocr/tesseract/tree/master/tessdata) including the history and use that new repository as a submodule for `tesseract` and `tessdata`, `tessdata_fast`, `tessdata_best`.

**Comment by Shreeshrii** [comment]
I like the alternative way better.

**Comment by Shreeshrii** [comment]
tesseract build instructions will need to be modified to update the config submodules.

**Comment by stweil** [comment]
Here is an example repository which could be used: https://github.com/stweil/tessconfigs.

**Comment by Shreeshrii** [comment]
Looks good. It has all the history too.

@zednop please create the new repo.

**Comment by zdenop** [comment]
it is not problem to create another repository. But can he get input from tesseract packages (e.g. Ubuntu), if we do not break something?

**Comment by stweil** [comment]
Creating the new repository won't break anything. The critical point comes later. Adding the new repository as a submodule to the `tessdata*` repositories should work without any problem, but adding the submodule to the `tesseract` repository needs more thoughts. The good news is that older version (3.x, 4.x) won't be affected, so Linux distributions based on 4.x won't have to change anything for now. They will have to update their build scripts for Tesseract 5.0.

**Comment by zdenop** [comment]
Yes, I do not expect problem on side of `tesseract-ocr/tessdata_fast` and `tesseract-ocr/tessdata_best`... (I doubt that ordinary user clone or download them ;-) ). 

But how to handle `tesseract-ocr/tesseract` repository? BTW what should be name of new repository? [tessdata](https://github.com/tesseract-ocr/tessdata) is already used...

**Comment by stweil** [comment]
Regarding name, @Shreeshrii suggested `tessdata_configs` and I suggested `configs` or `tessconfigs` (see comments above).

The `tesseract` repository will replace the files in the `tessdata` subdirectory by files from the new repository which must be added as a submodule, only in Git master of course. That requires updates of the documentation.

**Comment by Shreeshrii** [comment]
`tessconfigs` sounds good.

**Comment by zdenop** [comment]
done: https://github.com/tesseract-ocr/tessconfigs

**Comment by stweil** [comment]
I replaced the content with the files including the complete history from the `tesseract` repository and added your commit on top.

**Comment by stweil** [comment]
Now the pull request was updated to add the new `tessconfigs` submodule.

**Pull request merged**
